/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class Page3 extends javax.swing.JPanel {

    /**
     * Creates new form Page3
     */
    public Page3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonComprarProducto = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonActInfo = new javax.swing.JButton();
        jButtonRegistroPersonal = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        modelo = new DefaultTableModel();
        modelo.addColumn("NumReferencia");
        modelo.addColumn("Nombre");
        modelo.addColumn("Unidades");
        modelo.addColumn("Precio");
        jTable1.setModel(modelo);
        jScrollPane1.setViewportView(jTable1);

        jButtonComprarProducto.setText("Comprar Producto");
        jButtonComprarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarProductoActionPerformed(evt);
            }
        });

        jButtonCerrarSesion.setText("Cerrar sesion");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Productos a la venta");

        jButtonActInfo.setText("Editar Perfil");

        jButtonRegistroPersonal.setText("Registro personal de compras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonComprarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCerrarSesion)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActInfo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRegistroPersonal))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonComprarProducto)
                    .addComponent(jButtonCerrarSesion)
                    .addComponent(jButtonActInfo)
                    .addComponent(jButtonRegistroPersonal))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonComprarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActInfo;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonComprarProducto;
    private javax.swing.JButton jButtonRegistroPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelo;

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public JButton getjButtonComprarProducto() {
        return jButtonComprarProducto;
    }

    public JButton getjButtonCerrarSesion() {
        return jButtonCerrarSesion;
    }
    
    public JTable getjTable1() {
        return jTable1;
    }

    public JButton getjButtonActInfo() {
        return jButtonActInfo;
    }

    public JButton getjButtonRegistroPersonal() {
        return jButtonRegistroPersonal;
    }
   
}
