/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernando
 */
public class PageProvedoresPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PageProvedoresPrincipal
     */
    public PageProvedoresPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProvedores = new javax.swing.JTable();
        jButtonAgregarProvedor = new javax.swing.JButton();
        jButtonCrearPedido = new javax.swing.JButton();
        jButtonActualizarProveedor = new javax.swing.JButton();
        jButtonEliminarProveedor = new javax.swing.JButton();

        modelo = new DefaultTableModel();
        modelo.addColumn("NumReferencia");
        modelo.addColumn("Nombre");
        modelo.addColumn("Unidades");
        modelo.addColumn("Precio");
        jTable2.setModel(modelo);
        jScrollPane3.setViewportView(jTable2);

        setBackground(new java.awt.Color(204, 204, 255));

        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Telefono");
        modelo.addColumn("Direccion");
        modelo.addColumn("Producto");
        modelo.addColumn("Valor");
        jTableProvedores.setModel(modelo);
        jScrollPane4.setViewportView(jTableProvedores);

        jButtonAgregarProvedor.setText("AGREGAR PROVEEDOR");
        jButtonAgregarProvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarProvedorActionPerformed(evt);
            }
        });

        jButtonCrearPedido.setText("Crear Pedido");

        jButtonActualizarProveedor.setText("Actualizar info proveedor");
        jButtonActualizarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarProveedorActionPerformed(evt);
            }
        });

        jButtonEliminarProveedor.setText("Eliminar Proveedor");
        jButtonEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAgregarProvedor)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCrearPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarProveedor)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarProvedor)
                    .addComponent(jButtonCrearPedido)
                    .addComponent(jButtonActualizarProveedor)
                    .addComponent(jButtonEliminarProveedor))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarProvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarProvedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarProvedorActionPerformed

    private void jButtonActualizarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarProveedorActionPerformed

    private void jButtonEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarProveedor;
    private javax.swing.JButton jButtonAgregarProvedor;
    private javax.swing.JButton jButtonCrearPedido;
    private javax.swing.JButton jButtonEliminarProveedor;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableProvedores;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelo;

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public JButton getjButtonAgregarProvedor() {
        return jButtonAgregarProvedor;
    }

    public JButton getjButtonCrearPedido() {
        return jButtonCrearPedido;
    }

    public JButton getjButtonActualizarProveedor() {
        return jButtonActualizarProveedor;
    }

    public JButton getjButtonEliminarProveedor() {
        return jButtonEliminarProveedor;
    }
     
    public JTable getjTableProvedores() {
        return jTableProvedores;
    }
       
}
